---
Name: rhinoroutes
After: 'coreroutes'
---
SilverStripe\Control\Director:
  rules:
#    'docs//$Action/$ID/$OtherID': 'DocumentationViewer'
    'RhinoAssessment_Controller//$Action/$ID' : DNADesign\Rhino\Control\RhinoAssessment_Controller

